### ISSUE TITLE
Should use a tree structure to organise experiments or should we keep a flat scheme?

### ISSUE THREAD

**Issue by Lawouach** [open-chaos/experiment-catalog#42]
Right now, experiments are using a flat structure and all live at the top-level. This will likely get out of hand quickly and doesn't really help quick discovery.

Should we at least have one level based on the target? Obviously, the question then becomes how to deal with experiments that cover two targets?

**Comment by russmiles** [comment]
It's an important question, especially given the way directories are not used by GH indexing, hence the recommendations around tag usage in the README, but when maximising for human ease of navigation at the source code repo level, then some organisation and nesting of directories may be desirable.
